### ISSUE TITLE
Can't tell direction?

### ISSUE THREAD

**Issue by kermit4** [tmo1/sms-ie#1]
Is the direction information unavailable?  I don't see any way to tell from the JSON.

I.e. if a message was one I sent or one I recieved.

**Comment by tmo1** [comment]
Direction information is present in the value of the the "type" tag. The two most common values are "1", which denotes "inbox", and "2", which denotes "sent". The meanings of the various possible values are specified here (in the "MESSAGE_TYPE_XXXX" constant definitions):

https://developer.android.com/reference/android/provider/Telephony.TextBasedSmsColumns

**Comment by kermit4** [comment]
Thank you!  And thank you for the app!  I love being able to grep my messages!

Here's some ugly shell code to make this line based for grepping in case anyone's curious:

jq -r < sms.json '.[]|select(.address=="+15555555555")|[ ( .date | tonumber / 1000  | todate ) , ( .type | tonumber == 1 ) , .body ] | @tsv '  |tac|awk '$2=="true"{$2="<them>"}$2=="false"{$2="<me>"}1'

**Comment by tmo1** [comment]
You're very welcome! It's gratifying to know that someone found this useful (especially someone with better shell / JSON skills than mine ;)).
