### ISSUE TITLE
Missing APK asset in v1.5.4 github release 

### ISSUE THREAD

**Issue by ishanarora** [tmo1/sms-ie#105]
Thanks for working on this project! The latest github release (v1.5.4) is missing the apk asset, instead has a zipped version of the apk. This is okay for when downloading manually, but it fails automated tools such as [Obtainium](https://github.com/ImranR98/Obtainium). It would be great if we could always include the apk asset directly as done with the prior versions. Thanks!

**Comment by tmo1** [comment]
I think that was just a mistake on my part - when uploading APKs to bug reports for testing, they have to be zipped, so I think I just got mixed up and uploaded a zipped version to this release instead of the usual APK. Fixed and thank you!

**Comment by ishanarora** [comment]
Thank you!
