### ISSUE TITLE
sms-ie crash when trying import

### ISSUE THREAD

**Issue by r4d1s** [tmo1/sms-ie#11]
Hello, i'm using lineageos 18.1 and when i'm trying to import  my .json file the apps shutdown. I made the export on the oneplus3 of my brother, his system was official oxygenOS (in android 8.0). I made 2 export, one with binary an the other one without the binary, both doesn't work. 
Once i made the export i updated the op3 oxygenOS android 8.0 to lineageos 18.1 (android 11). Do you have idea why i can't export the .json files ?

The apps sometimes works well, and sometimes it doesn't works and the apps crash and close directly when i try to import. I''m always runing on lineageos 18.1.

**Comment by tmo1** [comment]
1) What version(s) of the app was / were / is being used for the import and export?
2) A logcat of the crash log would help to track this down; [here](https://www.xda-developers.com/guide-sending-a-logcat-to-help-debug-your-favorite-app/) is a general tutorial, and [here](https://f-droid.org/en/docs/Getting_logcat_messages_after_crash/) is a guide focusing on the F-Droid client, but containing generally useful information.

**Comment by scbixi** [comment]
Hi tmo, thanks for the app.
I have the same problem, export from a stock android 6 to a lineageos 17.1.

Here the interesting part of the log:
```
01-01 10:01:48.797  1683  1922 E SQLiteLog: (1) table sms has no column named pri
01-01 10:01:48.797  1683  1922 E SQLiteDatabase: Error inserting date=1640940097995 creator=com.github.tmo1.sms_ie address=+33 6 xx xx 55 49 date_sent=0 read=1 sub_id=7 pri=0 type=2 body=message content seen=1 thread_id=1 stack_type=0 failure_cause=-1 error_code=0 locked=0 status=-1
01-01 10:01:48.797  1683  1922 E SQLiteDatabase: android.database.sqlite.SQLiteException: table sms has no column named pri (code 1): , while compiling: INSERT INTO sms(date,creator,address,date_sent,read,sub_id,pri,type,body,seen,thread_id,stack_type,failure_cause,error_code,locked,status) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
```

So column pri not in destination db. Hope it helps.

**Comment by r4d1s** [comment]
> 1. What version(s) of the app was / were / is being used for the import and export?
> 
>     2. A logcat of the crash log would help to track this down; [here](https://www.xda-developers.com/guide-sending-a-logcat-to-help-debug-your-favorite-app/) is a general tutorial, and [here](https://f-droid.org/en/docs/Getting_logcat_messages_after_crash/) is a guide focusing on the F-Droid client, but containing generally useful information.

1 > I'm using the v1.3
2 > Still gonna look for a logcat

**Comment by tmo1** [comment]
> Edit : deleted pri, failure_cause and stack_type fields, now it's working well.

Thanks for the report! It seems, then, that the problem (at least the one you hit) is that older versions of the message database had some columns that have been removed in more recent ones, and so the app crashes when it tries to insert the values into the no longer existing columns. A fix should be simple enough; I'll write and test one and report back here.

**Comment by tmo1** [comment]
I added code that drops all fields that don't exist in the current databases, and in my testing this fixes the problem, so I closed the bug. It would be great if you could either confirm the fix or report that it remains.

**Comment by r4d1s** [comment]
Should i need to reinstall the 1.3 from github to try the fix ?

**Comment by tmo1** [comment]
Yes, you'll need to checkout and build a fixed version. If you want, I can upload an APK.

**Comment by r4d1s** [comment]
> Yes, you'll need to checkout and build a fixed version. If you want, I can upload an APK.

Yes please for the apk.
