### ISSUE TITLE
Add support for monochromatic adaptive launcher icons

### ISSUE THREAD

**Issue by stefan-niedermann** [tmo1/sms-ie#114]
As described here: https://developer.android.com/develop/ui/views/launch/icon_design_adaptive#user-theming

🚀 🙂

**Comment by tmo1** [comment]
Hi,

I don't know icon design, and so I do not do more of it than necessary. If you or anyone else wants to add such support, a pull request is welcome.

**Comment by Biswa96** [comment]
I have tried to add a monochrome icon in sms-ie application. Here is a screenshot of that icon.

![image](https://github.com/tmo1/sms-ie/assets/31443074/087df83f-2e40-4738-b7e3-d10bea9cea5b)

I am not sure if it is appropriate. Please let me know if any changes are required. I can try to add that in a pull request.

**Comment by tmo1** [comment]
Thank you for working on this, but I don't know enough about icon design or Android's rules for adaptive icons to know what to do with this. If you create a PR and explain / show what your icon does, I can review it.
