### ISSUE TITLE
Latest release can't import JSON backup

### ISSUE THREAD

**Issue by bradgranath2** [tmo1/sms-ie#117]
I have backups from a previous version that are in a raw .json file. The latest release won't allow me to select it because it isn't a zip file.  I tried zipping the json file, and while the selection screen allowed me to choose the file, after attempting to parse it, the app responds with:

> "**Can't find 'messages.ndjson'** 
Please make sure that the provided file is a ZIP file in the correct format 
[OKAY]"

Any chance we could get the ability to import old backups?

If not, which release should I revert to?

**Comment by tmo1** [comment]
From the forthcoming documentation:

> Version 2.0.0 introduced a major rewrite of the SMS and MMS messages import / export code, implementing a new message storage format:
> 
>  - The messages are now stored in a [Newline-delimited JSON](https://en.wikipedia.org/wiki/JSON_streaming#Newline-Delimited_JSON) file (always named `messages.ndjson`), as opposed to the standard JSON previously used.
>  
>  - Binary MMS data is now stored separately from message text data and metadata; the `messages.ndjson` file, along with a `data/` directory containing the MMS binary data files copied directly from the Android filesystem (with their original filenames), are both encapsulated in a ZIP file.
>  
>  - All (ND)JSON tags added by SMS Import / Export are now prefixed with a double underscore (e.g., `__display_name`, `__parts`), to clearly indicate that they have been added by the app.
> ...

> **These format changes unfortunately render versions of the app from 2.0.0 and on incompatible with JSON message files produced by earlier versions of the app.** A conversion tool may eventually be released; as of now, however, if re-exporting messages using the current version of the app is not feasible, then the latest version of the app prior to version 2.0.0 should be used to import message JSON files produced by versions of the app prior to version 2.0.0.

**Comment by bradgranath2** [comment]
Thanks so much for this app!  The docs are great, and it sounds like I was just caught in middle of an update.   Thanks!

**Comment by tmo1** [comment]
> Thanks so much for this app! The docs are great, and it sounds like I was just caught in middle of an update. Thanks!

You're very welcome! As you surmise, I haven't posted the updated documentation since the new version is still only a pre-release.

**Comment by mjeammet** [comment]
Same thing here, I exported my messages before updating (v1.5.4 probably) and was trying to import it today (v2.0.0), without success. 

Thank you, I installed 1.5.4 again and it worked perfectly ! 🚀
