### ISSUE TITLE
importing messages not possible

### ISSUE THREAD

**Issue by MolendijkM** [tmo1/sms-ie#120]
Hi, I am having an issue with importing messages. Importing calls and contacts worked fine, but when I try to import messages, they are all greyed out. smsimportexport is the default sms app. the messages are in the .json format, and when I open one in text editor they have content. I tried re-installing the app but this did not help. How can I import my sms messages?

edit
I have to point out that the files were created with sms-ie itself (scheduled export, with removal of old exports (which were not deleted by the way))

**Comment by crosenbe** [comment]
Same issue here. Only files with .json suffix are enabled to import messages.

**Comment by crosenbe** [comment]
It seems the json structure was not exported as array but an array is expected. I extracted the json file from the zip and modified it in a simple manner.

Original version
```
{ <record> }
{ <record> }
{ <record> }
```

Modification
```
[
{ <record> },
{ <record> },
{ <record> }
]
```
I pushed the json file to my device and the import was successful but i lost my MMS in case i pushed the json and not the zip.

**Comment by aa755** [comment]
I have an old .json export. Now I want to import it to my new phone where the app expects a .zip import. is there a way to convert?

**Comment by tmo1** [comment]
Please see [issue #117](https://github.com/tmo1/sms-ie/issues/117). If you still have trouble, please report the problem with more details, including the version of the app used to export and import.

**Comment by tmo1** [comment]
I'm closing this issue on the assumption that the problems reported here all stem from the `v1` - `v2` transition, and can be resolved using the methods I link to above. If any problems remain, please reopen the issue and provide more detail.

**Comment by aa755** [comment]
my problem was resolved using the methods you linked, thanks

**Comment by tmo1** [comment]
> my problem was resolved using the methods you linked, thanks

Thanks for letting me know!
