### ISSUE TITLE
Toast notification does not fit

### ISSUE THREAD

**Issue by Artem13327** [tmo1/sms-ie#122]
![IMG_20230722_183335](https://github.com/tmo1/sms-ie/assets/68551925/6f650071-ec93-4c51-b505-7dd9dd8e30cf)

**Comment by tmo1** [comment]
Which toast is this?

**Comment by tmo1** [comment]
The problem seems to be that, as per the [Android documentation](https://developer.android.com/guide/topics/ui/notifiers/toasts),

> If your app targets Android 12 (API level 31) or higher, its toast is limited to two lines of text and shows the application icon next to the text. Be aware that the line length of this text varies by screen size, so it's good to make the text as short as possible.

I'd rather not rewrite the app just to solve this problem - is there any way you can shorten the Russian translation of the notification text?
