### ISSUE TITLE
Contacts Import/Export support

### ISSUE THREAD

**Issue by DI555** [tmo1/sms-ie#127]
Many thanks for a great app!

Is it possible to implement and contacts import/export also?
..yes, that function exists in android contacts, but better it to be in a one place like smsie; and we have a huge danger that G may delete it, like it did with android sms & calling finctions((.

**Comment by tmo1** [comment]
Thank you! The app does implement Contacts import and export, although this functionality needs improvement - see issues #52, #68, and #76.

**Comment by tmo1** [comment]
Thank you! The app does implement Contacts import and export, although this functionality needs improvement - see issues https://github.com/tmo1/sms-ie/issues/52, https://github.com/tmo1/sms-ie/issues/68, and https://github.com/tmo1/sms-ie/issues/76.

**Comment by tmo1** [comment]
Thank you! The app does implement Contacts import and export, although this functionality needs improvement - see issues https://github.com/tmo1/sms-ie/issues/52, https://github.com/tmo1/sms-ie/issues/68, and https://github.com/tmo1/sms-ie/issues/76.
