### ISSUE TITLE
BUILDING.md link in README.md is incorrect

### ISSUE THREAD

**Issue by dshepsis** [tmo1/sms-ie#130]
Under the [Installation](https://github.com/tmo1/sms-ie#installation) section of the readme, there is a link "For instructions on building the app from its source code, see [`BUILDING.md`](https://github.com/tmo1/sms-ie/BUILDING.md)." with the link address `https://github.com/tmo1/sms-ie/BUILDING.md`. The link leads to "Not Found" error page. I believe the link address should instead be `https://github.com/tmo1/sms-ie/blob/master/README.md`.

**Comment by tmo1** [comment]
Fixed - thanks!
