### ISSUE TITLE
SMS + MMS restore is _STILL_ totally broken ***DO NOT CLOSE****

### ISSUE THREAD

**Issue by capybara-overdose** [tmo1/sms-ie#148]
**OLD THREAD INCORRECTLY CLOSED, THIS PROBLEM STILL REPEATS WHEN TESTED  AS OF 26/12/23 **

App is worse than useless - trick you into thinking you have made a backup but then doesnt work when you restore!!

MMS have no photos.

Many SMS just say "Subject:" and half a sentence.

Many SMS have no text at all.

2000 + work SMS LOST/TOTALLY USELESS now - thanks a lot >:(

(dont' tell me "WeLl YoU ShoUlD BaCk Up yOuR DaTa" - this was supposed to BE the backup!!)

**Comment by TwisX** [comment]
Same here. No photos and many blank messages.

**Comment by tmo1** [comment]
> Same here. No photos and many blank messages.

Hi,

Please follow [these issue reporting guidelines](https://github.com/tmo1/sms-ie#bugs-feature-requests-and-other-issues), and I'll take a look.

**Comment by tmo1** [comment]
@TwisX has not responded to my message, so I'm closing this issue.

@capybara-overdose: [as I previously told you](https://github.com/tmo1/sms-ie/issues/144#issuecomment-1849207962), I'm not going to engage you unless / until you are prepared to be polite. **Please do not** open yet another issue for the same problem. If you are prepared to be polite, you may continue the discussion here (you can still comment even after the issue has been closed).
