### ISSUE TITLE
Remove title_activity_settings

### ISSUE THREAD

**Issue by Artem13327** [tmo1/sms-ie#153]
It just seems to me that nothing will change for the majority, but translators won’t have to see the confusing line once again

And also here is a link to a comment not written by me https://hosted.weblate.org/translate/sms-import-export/ui-strings/ru/?checksum=b56dd24f3007df06

**Comment by tmo1** [comment]
I'm sorry, but I'm not sure what you're proposing - please explain more clearly. And I'm not sure what comment you're referring to.
