### ISSUE TITLE
Bug: app hangs on "Wiping SMS messages ..."

### ISSUE THREAD

**Issue by thoelze1** [tmo1/sms-ie#155]
sms-ie version: 2.3.0
android version: 14
description: app fails to wipe messages (or takes incredibly long to do so, longer than a full messages export)
to reproduce: set app as default SMS app (as necessary) and click "WIPE MESSAGES"

**Comment by tmo1** [comment]
I just ran a wipe on an (emulated) Android API level 34 system with 2000+ SMS and 15,000+ MMS messages, and it completed without error in about ten minutes. How many messages are on your system, and how long did you wait? Also, [please post a logcat](https://github.com/tmo1/sms-ie#logcat).

**Comment by tmo1** [comment]
Closing due to reporter unresponsiveness; feel free to reopen with further details.
