### ISSUE TITLE
Require a checkbox or something else in a window asking you to set the application as default

### ISSUE THREAD

**Issue by Artem13327** [tmo1/sms-ie#162]
Something like, "YES I KNOW THE CONSEQUENCES OF SETTING THIS APPLICATION AS THE DEFAULT"

**Comment by tmo1** [comment]
There's already [a warning](https://github.com/tmo1/sms-ie/blob/1306c54537557ff708296ad283c0f5d5695248ed/app/src/main/res/values/strings.xml#L94) displayed to the user before asking to become the default app:

> SMS Import / Export must be the default SMS app in order to import or wipe messages. Please read the README and make sure you understand the implications of doing this before proceeding.
