### ISSUE TITLE
Crash when exporting MMS Binary Data

### ISSUE THREAD

**Issue by n21brown** [tmo1/sms-ie#166]
Samsung S24
OneUi 6.1 / Android 14

Install app. Open app and grant all permissions. Click 'Export Messages'. SMS export runs and finishes. MMS export starts then crashes. A partial is file left over.

Turning off 'Export Binary MMS Data' seems to stop the process crashing.

Due to the data being exported in a bloated JSON file it cannot be verified easily.

**Comment by tmo1** [comment]
What version of the app are you using? [Logcat](https://github.com/tmo1/sms-ie#logcat)?

**Comment by tmo1** [comment]
Closing due to reporter unresponsiveness; feel free to reopen with further details.
