### ISSUE TITLE
Imported MMS are visible as just "white space"

### ISSUE THREAD

**Issue by danvac** [tmo1/sms-ie#17]
Hello. I am trying to export/import messages from Motorola G6 Plus to OnePlus Nord 2 5G.
Telephone contains a lot of messages. About 13000 SMS and 1000 MMS.

I have gotten into two issues. If I tried to export everything from G6 Plus app crashes.

So I had just exported MMS using debug mode. Now when I import those messages in OnePlus Nord 2, it does show threads and "messages", but there are not any image visible, just empty spaces.

Can you let me know which information you want to share. Idealy in some private channel.

**Comment by danvac** [comment]
I was able to workaround it using different application. Closing.

**Comment by ckuethe** [comment]
> I was able to workaround it using different application. Closing.

@danvac which app? I've got about 140k SMS and MMS to copy and restore...
