### ISSUE TITLE
wipe messages not work on android 14

### ISSUE THREAD

**Issue by molitona** [tmo1/sms-ie#174]
i exported messages using https://play.google.com/store/apps/details?id=com.riteshsahu.SMSBackupRestore
from one android 7 phone as xml file
then imported it using "import messages" feature here https://github.com/FossifyOrg/Messages (it's sms app i use) to my android 13 other phone which got upraded to android 14 these days.

after that i wanted to delete all msgs from my phone. i used fossify messages and after removing all of them they got reloaded instantly

i used ur app to wipe messages but the same problem happens

i cleared data/cache of com.android.providers.telephony (phone and messaging storage) + fossify messages to no avail

help pls!

**Comment by tmo1** [comment]
Is it possible that [Google's backup service](https://support.google.com/android/answer/2819582), or something similar, is running on the phone?

**Comment by molitona** [comment]
i don't have google acc active or any other google app on my phone except aosp needed ones (debloated them with adb)

**Comment by tmo1** [comment]
I don't know what the problem is, but if IIUC, it occurs with message deletion via the Fossify app as well as message deletion via SMS I/E, which suggests that there's some problem with your Android installation rather than with SMS I/E. You've mentioned that you did some debloating - disabling system apps can sometimes cause strange problems. I'd be interested to know whether the problem can be reproduced on a fairly normal / stock Android installation.

**Comment by molitona** [comment]
i figured out that after wiping msgs using ur app and exporting them importing them it says 0 msgs imported

i downloaded QUICK SMS/DEKU SMS from fdroid and they don't get deleted msgs at all. one of them has an option to sync from android db. i tried it and nothing added which confirmed to me that local sms db is empty indeed.


it's a very strange prblm with fossify app. whenever i delete a msg it gets reloaded automatically with no body content, just title!!
deleted + reinstalled it and it has the same prblm

**Comment by molitona** [comment]
btw has com.android.providers.telephony pkg something to do with local sms db, what is its purpose?

**Comment by tmo1** [comment]
> it's a very strange prblm with fossify app. whenever i delete a msg it gets reloaded automatically with no body content, just title!!

At this point, it sounds like the problem may be with the Fossify app. You can try reporting it on its issue tracker.

**Comment by molitona** [comment]
yep thank u anyway

**Comment by molitona** [comment]
> btw has com.android.providers.telephony pkg something to do with local sms db, what is its purpose?

any resp?

**Comment by tmo1** [comment]
> btw has com.android.providers.telephony pkg something to do with local sms db, what is its purpose?

I'm not sure exactly what's in that package, but the official Android documentation describes its [Telephony provider](https://developer.android.com/reference/android/provider/Telephony) (`android.provider.Telephony`) as follows:

> The Telephony provider contains data related to phone operation, specifically SMS and MMS messages, access to the APN list, including the MMSC to use, and the service state.

**Comment by molitona** [comment]
thank u so much
