### ISSUE TITLE
Status notifications permanently stuck

### ISSUE THREAD

**Issue by haarp** [tmo1/sms-ie#179]
Hello,

I'm using v. 2.3.2 from F-Droid. I have scheduled export activated with export being dumped to Nextcloud SAF location. Messages and Calls are enabled.

Every night when the dump finishes, the "Scheduled export executing" notification remains. I can see the calls and messages files ending up on Nextcloud, so the dump appears to finish.

This problem started after a recent upgrade, probably 2.3.1. I currently get rid of the notifications by manually disabling all notifications for the app, then re-enabling them.

Thanks!

**Comment by tmo1** [comment]
Thanks for reporting this. I have reproduced the problem, and am working on figuring it out.
