### ISSUE TITLE
Problem importing call logs

### ISSUE THREAD

**Issue by regs01** [tmo1/sms-ie#185]
Export went fine, but on import i'm getting an error

```
Error importing call log
Error parsing JSON:
"java.lang.IllegalArgumentException: column 'LAST_SEVEN_NUMBER' is invalid"
```

**Comment by tmo1** [comment]
https://github.com/tmo1/sms-ie#bugs-feature-requests-and-other-issues

**Comment by tmo1** [comment]
Closing to due submitter unresponsiveness.
