### ISSUE TITLE
[Feature request] Calls deduplication

### ISSUE THREAD

**Issue by ngocanhtve** [tmo1/sms-ie#189]
Dear,

Now the message deduplication feature is working well, would you consider adding the feature to call logs?

Thanks!

**Comment by tmo1** [comment]
Duplicate of #176

**Comment by tmo1** [comment]
[This has already been implemented](https://github.com/tmo1/sms-ie/commit/69d2f95b9b1f0eb41168330707cf9f47f2004e5e), and will be available in the next release, which I hope to push within a day or two.

**Comment by ngocanhtve** [comment]
It worked. Thank!

**Comment by tmo1** [comment]
> It worked. Thank!

You're welcome! Thanks for your translation work.
