### ISSUE TITLE
New icon suggestion

### ISSUE THREAD

**Issue by Donnnno** [tmo1/sms-ie#20]
less text, more graphics :)

![image](https://user-images.githubusercontent.com/31142286/159125287-69d175e1-f588-4ce3-976b-8e95c4a9f628.png)

Maybe something like this

**Comment by tmo1** [comment]
Looks pretty good! Is the blue background part of the icon?

**Comment by Donnnno** [comment]
Yeah, if you like it:) 

I can change the colors too if you have any suggestions

**Comment by tmo1** [comment]
I'm not great at visual design - I just wasn't sure if it would look better with the background or without it. I don't have any suggestions about the color.

**Comment by tmo1** [comment]
Unless you have any further suggestions or improvements, why don't we try this one. If you create a PR with it, I'll see what it looks like on the phone, and I'll merge it if it looks good.

**Comment by Donnnno** [comment]
Yeah sure, sorry almost forgot it. I'll try it later today!

**Comment by maverick74** [comment]
@Donnnno Any idea for the icon if @tmo1 eventually accepts and implements contacts backup?
(yeah, I have a deep faith it will eventually get accepted ahahah - just joking... I'm just curious about how that would look)

**Comment by Donnnno** [comment]
Haha

**Comment by maverick74** [comment]
> Haha

https://github.com/tmo1/sms-ie/issues/26#issuecomment-1220969866

;)
