### ISSUE TITLE
"Unknown sender" when importing MMS messages

### ISSUE THREAD

**Issue by nybblr** [tmo1/sms-ie#213]
I'm on the latest stable GrapheneOS (Android 14) with a Pixel 7. I'm importing a SMSIE backup made with 2.4.0, using 2.4.0, and struggling to get MMS messages to show a sender. On both the backup and restore device, I'm using Google Messages.

All the messages import successfully (everything else looks good), and the entry in messages.ndjson looks good at a glance, but MMS messages directed to me (which are usually to multiple people) show up in Google Messages as "Unknown sender". I also checked with Graphene's default Messaging app, and the info on the message says "From: Hidden sender address".

![Screenshot_20240917-190041](https://github.com/user-attachments/assets/fdf0fbf0-e02d-43f2-87e5-3efcb0b39f6b)

Here's one of the messages giving me trouble (formatted, plus phone numbers and a few IDs redacted). The original phone numbers are in the same format of 10 digits, no spaces or non-digits:

```json
{
    "_id": "43897",
    "thread_id": "43",
    "date": "1726518279",
    "date_sent": "1726518275",
    "msg_box": "1",
    "read": "1",
    "m_id": "RED000000000000000000000",
    "ct_t": "application\/vnd.wap.multipart.related",
    "ct_l": "http:\/\/RED.D0.00.00\/servlets\/mms?message-id=RED00000000000000000000001",
    "m_cls": "personal",
    "m_type": "132",
    "v": "16",
    "m_size": "767",
    "pri": "129",
    "tr_id": "proto:RED000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
    "d_rpt": "129",
    "locked": "0",
    "sub_id": "2",
    "seen": "1",
    "creator": "com.google.android.apps.messaging",
    "text_only": "1",
    "__sender_address": {
        "_id": "150429",
        "msg_id": "43897",
        "address": "6666661111",
        "type": "137",
        "charset": "106",
        "sub_id": "2",
        "__display_name": "Alice"
    },
    "__recipient_addresses": [
        {
            "_id": "150428",
            "msg_id": "43897",
            "address": "6666662222",
            "type": "130",
            "charset": "106",
            "sub_id": "2",
            "__display_name": "Bob"
        },
        {
            "_id": "150430",
            "msg_id": "43897",
            "address": "666666333",
            "type": "151",
            "charset": "106",
            "sub_id": "2"
        }
    ],
    "__parts": [
        {
            "_id": "62277",
            "mid": "43897",
            "seq": "-1",
            "ct": "application\/smil",
            "name": "smil.xml",
            "chset": "3",
            "cid": "<smil>",
            "cl": "smil.xml",
            "text": "<smil>\r\n    <head>\r\n        <layout>\r\n            <root-layout width=\"240\" height=\"160\"\/>\r\n            <region id=\"Image\" width=\"100%\" height=\"67%\" left=\"0%\" top=\"0%\" fit=\"meet\"\/>\r\n            <region id=\"Text\" width=\"100%\" height=\"33%\" left=\"0%\" top=\"67%\" fit=\"meet\"\/>\r\n        <\/layout>\r\n    <\/head>\r\n    <body>\r\n    <par dur=\"8000ms\"><text src=\"text.000000.txt\" region=\"Text\"\/><\/par><\/body>\r\n<\/smil>",
            "sub_id": "2"
        },
        {
            "_id": "62278",
            "mid": "43897",
            "seq": "0",
            "ct": "text\/plain",
            "name": "text.000000.txt",
            "chset": "106",
            "cid": "<text.000000>",
            "cl": "text.000000.txt",
            "text": "Sure I'll probably just be reading most of the evening lol when do y'all usually wrap up?",
            "sub_id": "2"
        }
    ]
}
```

I tried the import process several times, each time wiping all messages and clearing cache / storage for each messaging app. I'm using default options in SMSIE to import.

It seems like the sender address is not being set/imported, though it does look like that attribute was backed up. Any ideas?

**Comment by tmo1** [comment]
Thanks for reporting this. The solution turns out to have been simpler than anticipated: While previous commits provided for setting the `sub_id` to `-1` [in the main MMS message metadata](https://github.com/tmo1/sms-ie/commit/c56fa0e7d65cf44b69e3698bd3fe9e38a81850a9) and [the MMS part metadata](https://github.com/tmo1/sms-ie/commit/9dcff764848c20f49ef95f57e4b29beb8ad17ec1), these did not apply to the MMS **address** metadata, since I had never encountered `sub_id`s there (and [the API documentation](https://developer.android.com/reference/android/provider/Telephony.Mms.Part) makes no mention of `sub_id`s there). Extending those commits to the MMS address metadata fixes this issue.
