### ISSUE TITLE
Feature Request: Export to Google Drive option or other cloud choices

### ISSUE THREAD

**Issue by jringbox** [tmo1/sms-ie#214]
I really like the improvements to this app and have been using it.  But there is one thing that annoys me.

While sms-ie does provide export with a scheduler, the only choice is storage on the actual phone.  If the phone dies for any reason, the scheduled backup has no worth.  Phones these days don't typically have removable sdcards anymore.  If they did, I would backup to the sdcard.

To get this backup to a online resource (such as Google Drive), I would have to use a third-party tool like FolderSync to sync files from my android.  But I rather not share my information with a third-party.  Security is kind of important to me and I really don't like to chance giving them access to my backup cell phone messages.

It would be nice if Google Drive could be an option for "Export to directory" settings option.

I know I can't really trust Google on privacy with Google Drive but at least it would be one less entity with possible access to my backup messages, calls, and contacts.

**Comment by tmo1** [comment]
> the only choice is storage on the actual phone

Actually, [SMS I/E has robust support for exporting to cloud storage](https://github.com/tmo1/sms-ie?tab=readme-ov-file#import--export-locations).

> To get this backup to a online resource (such as Google Drive), I would have to use a third-party tool like FolderSync to sync files from my android.

No such third-party tool is required. [Google Drive](https://developer.android.com/guide/topics/providers/document-provider), and any other cloud storage available through the Android Storage Access Framework, should be available as a storage location when exporting.

**Comment by jringbox** [comment]
I was not able to find any means to do as you mentioned.  Google Drive only allows upload but not "syncing".  I guess I will ask on the discussions if anyone has been able to do this.
