### ISSUE TITLE
GrapheneOS Default SMS permission issue

### ISSUE THREAD

**Issue by shadowcyberdeck** [tmo1/sms-ie#218]
Not sure what's going on, but I am not able to select this app as the default SMS option on pixel 9 pro XL running GrapheneOS v2024102100. Anytime Ibtry to switch its greyed out, and throws an error.  I've tried adjusting all the sandboxing features to no avail.  See screenshot. The underlined link doesn't go anywhere.  This worked a few months ago, so not sure what changed.

![Screenshot_20241022-174051.png](https://github.com/user-attachments/assets/fd808e2e-5a8e-48f8-ae95-2f7f44e50b58)

![3e427454-7ef6-4a7b-a73a-6fe03a3efe96.png](https://github.com/user-attachments/assets/468588a2-8f0f-494f-a8a7-414f4b974a4d)

**Comment by tmo1** [comment]
I'm not sure what's going on here, but it looks like GrapheneOS recently broke something with respect to default SMS app configuration: see various messages in [this thread](https://discuss.grapheneos.org/d/16519-grapheneos-version-2024101700-released).

**Comment by shadowcyberdeck** [comment]
Appears like it's related to that post. I'll run a few more tests tomorrow

**Comment by shadowcyberdeck** [comment]
Fixed the issue, for some reason I wasn't seeing the option described in this google help post last night: https://support.google.com/android/answer/12623953?hl=en

**Comment by Jackabomb** [comment]
I know this is closed, but in case it helps anyone else, I also got this same issue on LineageOS 22.2 today.
And like [shadowcyberdeck](https://github.com/shadowcyberdeck), I couldn't at first see any options for "allow restricted settings" in the three-dots menu, just an unhelpful "all permissions".
I think the app has to be closed or force stopped. Or it might be that you have to go to the page "the long way" through the settings menu.
Either way closing the app and opening settings separately did the trick and I was able to follow the linked instructions.
