### ISSUE TITLE
Import Export Signature Hash

### ISSUE THREAD

**Issue by stantonlarson** [tmo1/sms-ie#220]
Hello

I am trying to verify this app on Android Platform using AppVerifier and to do so I need the import export Signature Hash. Can you please provide such or tell me how to get it ?

Thanks

**Comment by tmo1** [comment]
Here's the SHA256 fingerprint of the signing certificate:

C1:05:E6:D9:67:55:42:D4:34:A9:CD:E9:DC:79:B2:49:F1:AC:0A:FC:3B:8A:AE:C7:D5:C8:20:11:36:CF:FD:BE

**Comment by stantonlarson** [comment]
It sin't matching with my app. How do I download this app from Github ?



Nov 11, 2024, 15:48 by ***@***.***:

**Comment by tmo1** [comment]
> It sin't matching with my app.

If you're getting the app from F-Droid, my understanding is that F-Droid uses its own certificate for app signing - you can ask in F-Droid support channels for more information about this.

> How do I download this app from Github ?

https://github.com/tmo1/sms-ie/#installation

**Comment by stantonlarson** [comment]
Are you guys able to post the app from Obtainium ?



Nov 11, 2024, 20:04 by ***@***.***:

**Comment by tmo1** [comment]
> Are you guys able to post the app from Obtainium ?

I'm sorry, but I don't understand what you're asking.

**Comment by stantonlarson** [comment]
I use the android Obtainium app to get the android applications but this sms app isn't available on that platform. 

The developer says sms  has to be posted to obtainium basically by anyone. I do not have the knowledge to do this. 




Nov 12, 2024, 09:50 by ***@***.***:

**Comment by tmo1** [comment]
> I use the android Obtainium app to get the android applications but this sms app isn't available on that platform.

I've never used Obtainium, but according to [its documentation](https://github.com/ImranR98/Obtainium/wiki#add-app-page), you should be able to just go to its "Add App" page and either add the SMS I/E url (`https://github.com/tmo1/sms-ie/`) or use Obtainium's search feature to find SMS I/E within the Github source.

**Comment by mrschyte** [comment]
> Here's the SHA256 fingerprint of the signing certificate:
> 
> C1:05:E6:D9:67:55:42:D4:34:A9:CD:E9:DC:79:B2:49:F1:AC:0A:FC:3B:8A:AE:C7:D5:C8:20:11:36:CF:FD:BE

Could this be added to the readme? It would be easier to find instead of searching through github issues.
