### ISSUE TITLE
optionally wipe sms database before restoring

### ISSUE THREAD

**Issue by ckuethe** [tmo1/sms-ie#23]
Thanks for writing this utility. I'm trying to restore a large number of SMS/MMS (~3.5GB json file) from a samsung galaxy to a google pixel. I've restarted this process a few times and unfortunately I now have a bunch of duplicated messages. I've tried various other apps to delete these messages as well as using adb (`adb shell pm clear com.android.providers.telephony`) none of which seem to work.

Since sms-ie can inject messages, it'd be great if it could clear the database before loading new messages.

**Comment by tmo1** [comment]
Adding database wiping functionality should indeed be easy enough. When testing (on emulator images), I typically just do factory resets, but I do see that wiping functionality could be useful. I don't know if / when I'll get to it, but I'll keep it in mind.

**Comment by tmo1** [comment]
Message wiping has been implemented.
