### ISSUE TITLE
Progress meter?

### ISSUE THREAD

**Issue by ckuethe** [tmo1/sms-ie#24]
Could there be a progress meter for importing and exporting messages? I don't mind waiting hours for messages to be imported as long as I know the process hasn't crashed.

**Comment by tmo1** [comment]
That's probably a good idea. I don't know if / when I'll get to it, but I'll keep it in mind as something to add.

**Comment by tmo1** [comment]
Progress reporting has been implemented.

**Comment by ckuethe** [comment]
Amazing! Thanks for implementing this request.
