### ISSUE TITLE
Import / export contacts

### ISSUE THREAD

**Issue by alexanderadam** [tmo1/sms-ie#26]
The [non-maintained Slight-backup](https://github.com/handschuh/Slight-backup) was able to export and import call logs.

It would be nice if sms-ie would fill that gap and would be extended to support other data for backup restore as well.

For instance for [contacts](https://github.com/handschuh/Slight-backup/blob/master/src/de/shandschuh/slightbackup/exporter/ContactsExporter.java).

**Comment by tmo1** [comment]
Android has [native](https://support.google.com/contacts/answer/7199294) contact export (to [VCF / vCard](https://en.wikipedia.org/wiki/VCard)) functionality. Is there some additional functionality you're interested in?

**Comment by alexanderadam** [comment]
Google Contacts isn't installed per default on every device and Google Services (i.e. PlayStore) aren't even available in every country (i.e. China).
Apart from that it would be great to have a single solution to backup and restore.

The featureset of [Slight-backup](https://github.com/handschuh/Slight-backup#readme) was great and designed to do that. But it's not maintained any more.
[SeedVault](https://calyxinstitute.org/projects/seedvault-encrypted-backup-for-android) is also a all-in-one solution but it's not compatible to stock ROMs because [it needs either platform keys or root access](https://github.com/seedvault-app/seedvault/issues/8#issuecomment-515891338).

So currently there's no FOSS solution left that works on stock ROMs without root and is backing up as much as possible.

**Comment by tmo1** [comment]
> Google Contacts isn't installed per default on every device and Google Services (i.e. PlayStore) aren't even available in every country (i.e. China).

Google Mobile Services are not required to export and import contacts (to VCF) from the Contacts app. But I did not realize that the app itself is not always available. I use LineageOS without GApps, which still comes with a working version of the Contacts app, so it's clearly open source and commonly available, but if it's actually common for it to not be available, I would consider adding contacts import / export functionality to SMS Import / Export.

>  Apart from that it would be great to have a single solution to backup and restore.

Fair enough, but I have to consider whether this is sufficient motivation to add the functionality to SMS Import / Export.

**Comment by Surendrajat** [comment]
@tmo1
> Is there some additional functionality you're interested in?

Yes. Periodic backup for contacts.

Currently, this feature is only available from some third-party apps like Super Backup. After SMS & Call logs periodic backup, I'll very much like to use just one app for contacts too.

**Comment by tmo1** [comment]
Okay, I'll consider adding contacts import / export functionality. It'll probably depend on how straightforward and  how similar to the app's existing import / export logic the code would be.

**Comment by maverick74** [comment]
I'm also very interested in this.

Is it expected any time soon?

Currently I'm using Comodo Backup to backup SMS+MMS+Contacts but I would prefer a FOSS alternative that would do all this in just one app.

**Comment by tmo1** [comment]
> Is it expected any time soon?

I haven't yet definitely decided to implement this, and I'm afraid I don't have a timeline, but the more people who express interest, the more likely that I'll do it, and sooner rather than later ;)

**Comment by tmo1** [comment]
Since several people have expressed significant interest in contacts import / export, I think I'm going to implement it. If there are no unexpected significant difficulties, it should be done within a week or two.

**Comment by maverick74** [comment]
This is a dream come true! 
Finally I'll be able to dump comodo backup for something open-source, offline and updated I can really trust!!!

**Comment by tmo1** [comment]
> Many thanks to you @tmo1

You're very welcome!

I have implemented experimental contacts export support and pushed it to the public repository. As documented in the [README](https://github.com/tmo1/sms-ie#contacts-1), the exported JSON is pretty cluttered and full of repetitious and redundant data, but the function does seem to work. Testing and feedback are appreciated.

I have not yet implemented import, but will hopefully do so soon.

**Comment by tmo1** [comment]
Contacts export and import have now been implemented and pushed to the repository, and will be included in the next release. This functionality should still be considered experimental, but it does work, at least in my testing. Again, testing and feedback are appreciated
