### ISSUE TITLE
Import Fails after ~27,000 SMS and ~21,000 MMS

### ISSUE THREAD

**Issue by gregordinary** [tmo1/sms-ie#28]
I have a backup taken from an Asus Zenfone 8 Flip, running Android 12. JSON is about 15GB. 
I've attempted the import twice. It gets through all ~27,000 SMS messages on import, however the application suddenly quits after it gets to around 21,000 **MMS** messages imported. That's out of about 48,000 MMS. 

The JSON includes the binary data / images in the MMS as well.

**Comment by tmo1** [comment]
Thanks for reporting this. Please specify the version of the program used for export and import, and please provide a logcat.

**Comment by gregordinary** [comment]
SMS Import / Export Version 1.4.1

I also tested this on a OnePlus 5T running Android 10 with the same results. Not certain if it fails at precisely the same point, but it's certainly close. 

Attached some relevant logs from each device, filtered for tmo1. 

- [Asus_Zenfone_8_Flip_logcat_05-29-2022_13-36-31.txt](https://github.com/tmo1/sms-ie/files/8793928/Asus_Zenfone_8_Flip_logcat_05-29-2022_13-36-31.txt)

- [OnePlust_5T_logcat_05-29-2022_13-33-42.txt](https://github.com/tmo1/sms-ie/files/8793929/OnePlust_5T_logcat_05-29-2022_13-33-42.txt)

They both seem to contain the following "unable to find or allocate a thread ID" error. 
```FATAL EXCEPTION: main
Process: com.github.tmo1.sms_ie, PID: 6287
java.lang.IllegalArgumentException: Unable to find or allocate a thread ID.
	at android.provider.Telephony$Threads.getOrCreateThreadId(Telephony.java:2277)
	at com.github.tmo1.sms_ie.ImportExportKt$importMessages$2.invokeSuspend(ImportExport.kt:610)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)```

**Comment by gregordinary** [comment]
Out of curiosity, I enabled debug options and had it import only MMS to see if it had more to do with total count, or just the MMS operation. This round it imported 0 SMS (as expected) and again failed at the same place between 20k & 21k MMS imported. I tested this on the OnePlus 5T. Same "Unable to find or allocate a thread ID".

**Comment by gregordinary** [comment]
Thanks for taking a look, I appreciate it! I re-ran the import on the older OnePlus 5T and it completed the import successfully. Looking through the logs, I don't see the same error repeated this time (on the 31st). I left the logs mostly unfiltered, only removed the wifi network info, other than that, everything is in tact. 

- [OnePlust_5T_05-31-2022_19-29-40.txt](https://github.com/tmo1/sms-ie/files/8810095/OnePlust_5T_05-31-2022_19-29-40.txt)

I see some errors about receiving texts because I didn't have it in Airplane Mode while running the import. Let me know if there's anything else I can run / dig up to assist!

**Comment by tmo1** [comment]
Thanks for the logs. If you do encounter the problem again, please see if you can reproduce it using the modified version of the app I provided above and capture the log. Beyond that, I'm not sure what more I can do at this point, without a way to reproduce and study the problem.

Thanks again, and please do report any further problems or relevant details that you encounter.
