### ISSUE TITLE
Wrong translation license

### ISSUE THREAD

**Issue by comradekingu** [tmo1/sms-ie#32]
https://hosted.weblate.org/projects/sms-import-export/ui-strings/#information says GPLv3-**only**
whereas
https://github.com/tmo1/sms-ie/search?q=any+later
dictates GPLv3-**or-later**.

This can be changed to "or-later" in
https://hosted.weblate.org/settings/sms-import-export/ui-strings/
and
https://hosted.weblate.org/settings/sms-import-export/glossary/
:)

**Comment by tmo1** [comment]
Thank you - fixed as per your suggestion.
