### ISSUE TITLE
Make unique notification channel for the specific types

### ISSUE THREAD

**Issue by tamas646** [tmo1/sms-ie#34]
Currently the app uses one notification channel (named 'notification_channel') for every notification (scheduled backup successful, scheduled backup unsuccessful...etc).

It would be great to have the notifications seperated to unique channels to be able to enable/disable them seperately. (for example to be able to disable only the 'scheduled update successful' notifications :wink:)

**Comment by tmo1** [comment]
Thank you for the suggestion - I'll consider implementing it. Given that at least currently, at most one scheduled backup takes place per day, is it really that useful to be able to disable that single daily success notification?

**Comment by tamas646** [comment]
(For me currently not, because the daily backups are not working due to an issue: [nextcloud/android#7846](https://github.com/nextcloud/android/issues/7846#issuecomment-1163215793). :D)

I don't say it's urgent and must have feature, but yes, I think it would be useful. If you have e.g. three apps that create daily backups, you will receive three notifications per day just to inform you that everything is fine. And this could be annoying at some point.
But the choice is yours, it's just a suggestion.

**Comment by tmo1** [comment]
> (For me currently not, because the daily backups are not working due to an issue: https://github.com/nextcloud/android/issues/7846#issuecomment-1163215793. :D)

Hm, I'm not sure I understand this, since we don't do any file renaming.

> I don't say it's urgent and must have feature, but yes, I think it would be useful. If you have e.g. three apps that create daily backups, you will receive three notifications per day just to inform you that everything is fine. And this could be annoying at some point.

> But the choice is yours, it's just a suggestion.

Got it. The changes to the code should be pretty simple, so I may just go ahead and do it.
