### ISSUE TITLE
Translate hebrow

### ISSUE THREAD

**Issue by Shopimisrel** [tmo1/sms-ie#46]
I translated your app into Hebrew, this is the translation code
How can I send you a string?

**Comment by Shopimisrel** [comment]
is there anyone here??

**Comment by tmo1** [comment]
Thank you for the translation! Would you please submit it via either of the two methods specified in [the CONTRIBUTIONS section of the README](https://github.com/tmo1/sms-ie#contributions)? If the directions there are unclear, just let me know and I'll clarify.
