### ISSUE TITLE
MMS Export support (feature request)

### ISSUE THREAD

**Issue by dngray** [tmo1/sms-ie#5]
Hi,

It'd be really good if this supported MMS export. I found that silence, qksms neither support MMS export. However [Simple-SMS-Messenger](https://github.com/SimpleMobileTools/Simple-SMS-Messenger) does.

Maybe this might be of some help with your implementation https://github.com/SimpleMobileTools/Simple-SMS-Messenger/blob/master/app/src/main/kotlin/com/simplemobiletools/smsmessenger/helpers/MessagesExporter.kt#L46

**Comment by tmo1** [comment]
Full MMS export is now in master; it will be included in the next release, which will hopefully take place soon.
