### ISSUE TITLE
Enhancement: Catch JSON parsing errors during import and show in application

### ISSUE THREAD

**Issue by xhajt03** [tmo1/sms-ie#59]
Hello, thanks for your application, I managed to import my several thousands text messages from about 14 years of using Nokia phones with Symbian now! Moreover, I like the fact that I can backup my messages using your application as well. However, I'd like to suggest to improve user friendliness of SMS IE by catching JSON parsing errors (and preferably other types of errors as well) and displaying some error message rather than simply crashing / dying. I had to create the import file by translating it to JSON from a CSV file (I created my own simple application running on a PC for that). While doing that, I had to discover and fix some bugs coming from differences in e.g. escaping certain characters in CSV and JSON, etc. However, I had to find these issues in the Android log retrieved using logcat rather than within the application, because the application simply crashed without providing any kind of feedback.

**Comment by tmo1** [comment]
> Hello, thanks for your application

You're welcome!

> I managed to import my several thousands text messages from about 14 years of using Nokia phones with Symbian now!

Wow, you managed to successfully import self-created JSON - that's impressive!

> However, I'd like to suggest to improve user friendliness of SMS IE by catching JSON parsing errors (and preferably other types of errors as well) and displaying some error message rather than simply crashing / dying.

This is probably worth doing. When I wrote the app, I wasn't really sure how much error checking to do. I've added some to address bug reports (e.g., #42), but I'm still not really sure how extensive to make these checks. I do agree that not crashing on unparseable JSON is a good idea, and I plan to implement this when I get a chance.

> I had to create the import file by translating it to JSON from a CSV file (I created my own simple application running on a PC for that).

I've actually been trying to provide a general solution to this sort of thing with SMS Import / Export's sibling project [sms-db](https://github.com/tmo1/sms-db). The development of the latter actually predates that of the former by a couple of years, but it has stagnated. I'd like to put some more work into it if / when I get a chance, and eventually get it to export to SMS Import / Export compatible JSON, and possibly to import messages from additional formats, such as CSV.

> While doing that, I had to discover and fix some bugs coming from differences in e.g. escaping certain characters in CSV and JSON, etc. However, I had to find these issues in the Android log retrieved using logcat rather than within the application, because the application simply crashed without providing any kind of feedback.

I'll just note that even if / when I add code to the app to catch exceptions thrown by unparseable JSON, I'll probably just have the app show a message that it can't parse the JSON, and refer the user to the logcat for more details - the app UI doesn't seem the right place for reporting the nitty-gritty technical details.

Thank you for reporting your experience and for the suggestion.

**Comment by xhajt03** [comment]
The error message raised by the JSON parser as an exception included the line and column number plus the discovered problem, i.e. not really very complicated and/or impossible to display in a UI (probably much easier to handle for a regular user than the procedure for accessing logcat ;-) ), but it's obviously up to you how the application should behave in case of such errors.

Creating the JSON based on the example created by exporting messages using your application wasn't really that difficult (as mentioned previously, I didn't create it manually, but rather created a simple text processing utility for that - I already created dozens of various simple tools for many different purposes in the last 30 years or so... ;-) ). In this case, I performed some preprocessing in a spreadsheet (LibreOffice) to transform fields included in the original CSV format created by Nokia Suite to the fields needed for import purposes, so my tool handled only the translation from the modified CSV to JSON. The most challenging part was translation of date and time into the format expected by SMS IE using a spreadsheet formula, especially considering the fact, that I had to find out the used date and time representation by experimenting.

**Comment by xhajt03** [comment]
Oops, sorry, I definitely didn't intend to close it...

**Comment by tmo1** [comment]
> The error message raised by the JSON parser as an exception included the line and column number plus the discovered problem, i.e. not really very complicated and/or impossible to display in a UI (probably much easier to handle for a regular user than the procedure for accessing logcat ;-) ), but it's obviously up to you how the application should behave in case of such errors.

I decided to implement a dialog box that shows the error itself, and directs the user to logcat for more information. I can always reconsider and add more information (e.g., line number) to the dialog box.

> Creating the JSON based on the example created by exporting messages using your application wasn't really that difficult (as mentioned previously, I didn't create it manually, but rather created a simple text processing utility for that - I already created dozens of various simple tools for many different purposes in Pascal during the last 30 years or so... ;-) ). In this case, I performed some preprocessing in a spreadsheet (LibreOffice) to transform fields included in the original CSV format created by Nokia Suite to the fields needed for import purposes, so my tool handled only the translation from the modified CSV to JSON.

> I'm still impressed (and also delighted that someone found the app useful in a way that I hadn't quite anticipated)!

> The most challenging part was translation of date and time into the format expected by SMS IE using a spreadsheet formula, especially considering the fact, that I had to find out the used date and time representation by experimenting.

Just to be clear, it's not my format, it's Android's - SMS I/E is just exporting and importing Android's internal date / time representation.

**Comment by xhajt03** [comment]
Thanks for the implementation. I'll be happy to test your changes once they're released.

And yes, I understand that the date / time format wasn't your invention. ;-)

**Comment by fanto666** [comment]
Hello!

@xhajt03:
> I managed to import my several thousands text messages from about 14 years of using Nokia phones with Symbian now! 

> I had to create the import file by translating it to JSON from a CSV file (I created my own simple application running on a PC for that).

I also have ~14 years backup of SMS from Nokia phone and would like to import it to android. Can you share the app or is it lost already?

Unfortunately I have little to no experience with JSON, but perhaps I could write something to get proper output.

FTR my output CSV from "Nokia Suite" (not Nokia PC Suite, that's older SW) looks like:

"sms","SENT,READ","","+421xxxxxxxxx","","2024.12.05 20:19","","Test"
"sms","READ,RECEIVED","+421xxxxxxxxx","","","2024.05.31 17:43","","test"

so I guess the fields are:
"sms",status,sender,recipient,"",date,"",message

where sender and recipients can be phone numbers or text fields, and message can be multiline.
MMS are not in output (I didn't find a way to export them).

**Comment by xhajt03** [comment]
Hi,

The program is by no means lost, don't worry, and you asked more or less at the right time for a Christmas present. ;-) It might need to be modified a bit, because the format used in SMS IE has changed in the meantime (from pure JSON to NDJSON), but I'm not sure - it may not make any difference in case of just SMS. I used an intermediate transformation of the original CSV file using a spreadsheet (I used Libre Office, but it would work with MS Excel equally well for sure), because I had to experiment with the date and time transformation a bit and once I already had the formulas created, it was easier to use them rather then to rework them in my program. I created my program in Free Pascal - I can compile it easily for MS Windows (32-bit or 64-bit), or for Linux (actually, even DOS would do ;-) ) - just tell me what you intend to use and I'll upload a compiled binary (together with the sources in case you want to have a look at them). I'm also willing to help with modifying the program if needed to suite the today's format used in SMS IE better - just let me know if you encounter any trouble.

Attached you'll find the template for the intermediate transformation and sources of my Pascal programs (and also of units needed for their compilation). As mentioned above, I'm ready to compile the sources for your preferred target environment / operating system and provide a link for downloading the resulting binary.
[sms_import_transformation_template.zip](https://github.com/user-attachments/files/18255332/sms_import_transformation_template.zip)
[sms2json.zip](https://github.com/user-attachments/files/18255334/sms2json.zip)
[th_units.zip](https://github.com/user-attachments/files/18255336/th_units.zip)

I don't remember any longer if I found a solution for MMS at that time, or if I had any MMS worth keeping. However, I found a tool named NbuExplorer allowing to export basically any data from Nokia backup files and I believe that you should be able to get the MMS content using this tool as well if you want to preserve them - translating it to the format supported by SMS IE shouldn't be difficult.

FWIW, I also created a program for translation of the exported favourite places/"landmarks" from Nokia Maps (I travelled quite a bit with my Nokia phones) to the GPX format, which may be used e.g. for importing into mapy.cz or Google Maps among others. I also played with the exported Contacts so that they could be imported into Google Contacts with all the details like the original address, etc. (I remember having faced some issues there, although I don't remember the details exactly any longer), and wrote a helper program for transformation of the exported VCF files for that purpose as well - let me know if you're interested in any of that as well. BTW, I didn't use SMS IE for importing the contacts, but used the application Contacts by your fellow countryman standing behind simplemobiletools.com.

Hope this helps

Tomas

**Comment by fanto666** [comment]
Hello,
I don't have much experience with freepascal (but I think you forgot to include contoolh.pas).

However:
I was able to convert CSV to required format using your office template.
Then I could directly into ndjson using python script in https://github.com/tmo1/sms-ie/issues/229#issuecomment-2617693790 

Unfortunately It seems that there is a bug in the template that causes output dates being 2 days later. I guess that's related to leap days (none in 1900)
