### ISSUE TITLE
Importing contacts requires permission to write Contacts

### ISSUE THREAD

**Issue by a-l-n** [tmo1/sms-ie#69]
Hello,

I have used SMS Import / Export to EXPORT CONTACTS and that works fine. However, when I try to IMPORT CONTACTS, I get the message "Importing contacts requires permission to write Contacts" (I don't even get a prompt for the location of the import file).
I get the same behaviour on Android 12 and LineageOS 19.
I have tried uninstalling the App > Installing a lower version = no luck, same message.
I have denied the App access to Contacts > Opened the app > Granted the app permissions to Contacts = no luck, same message.

Same behaviour on App Version: 1.5.1 and 1.5

Am I missing something? Can you please help?

Thank you

**Comment by tmo1** [comment]
I recently ran into the same problem in testing - I'm not quite sure why this hasn't arisen before. In any event, I think I fixed it in [this commit](https://github.com/tmo1/sms-ie/commit/a067c42920bb25b9ada3b39535dcbc3de13c9e99), so I'm closing this issue, but if you still experience the problem with the latest code, do reopen it.

**Comment by a-l-n** [comment]
Hi,

Thank you for your reply.

Since the latest release I could find is 1.5.1 (https://github.com/tmo1/sms-ie/releases), and your commit is after the release of 1.5.1, I tried building with "gradlew assembleDebug" (as per the Installation Readme). I've cloned this repo, installed gradle, ran ./gradlew assembleDebug from the root of the cloned repo and I started getting build errors - first being about missing the ANDROID_HOME environment variable in local.properties, which I defined (and created the directory), then the build failed because I need to accept SDK licence agreements and install the Android Studio SDK Manager.

At this stage, I was wondering if it's possible to get the apk file including your changes from somewhere (so I can just install and test the functionality)? 

I'm afraid trying to build the file myself, might lead me down a rabbit hole, spending a lot of time just configuring the build environment.

So, if it's possible, could I please grab the apk build containing your changes from somewhere? or I can wait for the new release if a new release is planned for the near future.


Thanks again!

**Comment by tmo1** [comment]
I'll probably release a new version in a few days. If you want an APK of the latest code before that, I can build one and post it here.

**Comment by a-l-n** [comment]
Thank you,

If you could build and post it here, that would be great!

**Comment by tmo1** [comment]
[Here's an APK of the latest code](https://github.com/tmo1/sms-ie/files/9957307/sms_ie-ask-for-write-contacts-permission.zip) - please confirm that it fixes the problem.

**Comment by a-l-n** [comment]
Awesome, thanks!

Give me a good few hours please as I can't give it a try right now.
Once I'm done testing it, I'll report back here.

**Comment by tmo1** [comment]
Thank you! I'll plan to release a version with this fix soon, then.

**Comment by a-l-n** [comment]
Excellent, I'll keep an eye for it (in F-Droid). Thanks again!
