### ISSUE TITLE
[feature request] Import from SMS-App Silence (xml-file)

### ISSUE THREAD

**Issue by ovz93br43v7** [tmo1/sms-ie#80]
Hi,

it would be great when import from the sms-app silence would be possible. https://f-droid.org/de/packages/org.smssecure.smssecure/

Background: Silence is not developed anymore, don't support export to android sms database. Export is only to a xml-file possible.

Thanks!

**Comment by tmo1** [comment]
Hello,

I do not plan to implement this in SMS I/E itself; a better place for such functionality would be the app's sibling project, [sms-db](https://github.com/tmo1/sms-db), one of the goals of which is to facilitate the conversion of message collections between different formats.

Development of sms-db has languished for a while, but I'm currently in the process of rewriting it from scratch in Python, with an improved and expanded database format. The initial rewritten version will only support SMS I/E's JSON format, but I plan to subsequently add support for other formats as well.

I'm closing this issue, but feel free to open a similar one as a feature request in sms-db, although I'm not promising to implement it.
