### ISSUE TITLE
Import / Reformat gammu init project

### ISSUE THREAD

**Issue by genofire** [tmo1/sms-ie#89]
Hello, is there any (good) dokumentation about the json format of this app?

I like to import (and maybe need to write an script for it) from an old phone.
Therefore i plan to use gammu, which has an ini based format:
https://docs.gammu.org/formats/smsbackup.html

**Comment by tmo1** [comment]
The JSON format is documented [here](https://github.com/tmo1/sms-ie#json-structure).

Duplicate: #55
