### ISSUE TITLE
Error Importing Messages.

### ISSUE THREAD

**Issue by azR-103** [tmo1/sms-ie#90]
Importing contacts and call logs working, but Importing message fails.

![Screenshot_2023-01-15-15-23-07-301_com github tmo1 sms_ie](https://user-images.githubusercontent.com/27334453/212535498-a61e9571-427d-4de9-834d-15119f5deea8.jpg)

**Comment by tmo1** [comment]
Have you temporarily [made SMS I/E the default messaging app](https://github.com/tmo1/sms-ie#permissions)?

**Comment by azR-103** [comment]
> Have you temporarily [made SMS I/E the default messaging app](https://github.com/tmo1/sms-ie#permissions)?

Yes.
This was happening only in miui stock rom, flashed lineageos based custom rom and it worked.

**Comment by tmo1** [comment]
`android.permission.WRITE_SMS` no longer exists in Android - it was [removed in API 23 (KitKat)](https://developer.android.com/sdk/api_diff/23/changes.html). SMS I/E requires Android API >= 23, so this shouldn't be an issue. What Android version is your MIUI ROM using?

**Comment by azR-103** [comment]
It was based on nougat. Nvm i have switched to custom rom & have no issue now.
